---
- hosts: all
  tasks: 
    - name: "Create a new database with name 'bobdata'"
      mysql_db: name=bobdata 
                state=present
    - name: Copy database file
      copy: 
        src: /root/mypdb.sql.gz
        dest: /tmp
    - name: restore databasee
      mysql_db: 
        name: bobdata
        state: import
        target: /tmp/mypdb.sql.gz 

    - name: dump all database to hostname.sql(remotehostname it should be in hosts file nagios.siqes.com )
      mysql_db:
        state: dump
        name: all
        target: /tmp/{{inventory_hostname}}.sql
    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        name: all
        state: import
        target: /tmp/{{inventory_hostname}}.sql
    
